#!/usr/bin/env bash

alias h='cd ~'
alias home='cd ~'
alias dotfiles='cd ~/.dotfiles'
alias ..='cd ..'
alias ...='cd ../..'

alias rake='noglob rake'
alias be='bundle exec'
alias mm='bundle exec middleman'
alias nom='rm -rf node_modules && npm cache clean && npm install'
alias bom='rm -rf bower_components && bower cache clean && bower install'
alias rmnm="find . -name 'node_modules' -exec rm -rf '{}' +"
alias r='bundle exec rails s'
alias guard='bundle exec guard'
alias rb='rbenv'
alias rdb='rake db:{reset,migrate}'
alias rpsql='rm /usr/local/var/postgres/postmaster.pid'
alias server='open http://localhost:1337 && python -m SimpleHTTPServer 1337'
alias js='cd app/assets/javascripts'
alias css='cd app/assets/stylesheets'

alias fs="stat -f '%z bytes'"
alias df='df -h'
alias ifi="ifconfig | ack 'net'"
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias untar='tar -xvvf'
alias reload='exec $SHELL -l'
alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'
alias dsremove='find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch'
alias dsr='find . -name ".DS_Store" -depth -exec rm {} \;'
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias flush="sudo dscacheutil -flushcache"

alias tls='tmux list-sessions'
alias tc='tmux new-session -s'
alias ta='tmux attach-session -t'
function tt {
  # opens teamocil backed sessions
  tmux new-session -d -s "${1}-tmp"
  tmux send-keys -t "${1}-tmp":1 "teamocil ${1}" C-m
  tmux attach-session -t ${1}
}

alias ls='ls -lah'
alias ll='ls -lth'

alias l1='tree --dirsfirst -ChFL 1'
alias l2='tree --dirsfirst -ChFL 2'
alias l3='tree --dirsfirst -ChFL 3'

alias ga='git add'
alias gs='git status -sb'
alias grm='git ls-files --deleted | xargs git rm'
alias undopush='git push -f origin HEAD^:master'
alias undocommit='git reset --soft HEAD~1'

alias proj="cd ~/proj/"
alias dev="cd ~/dev/"
