#!/usr/bin/env bash

alias ..='cd ..'
alias ...='cd ../..'
alias ls='ls -lah'
alias ll='ls -lth'
alias g='git'
alias ga='git add'
alias gs='git status -s'
alias gco='git checkout'
alias gp='git push' 
function gre() { git fetch origin; git checkout "$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@')"; git branch -D "$@"; git checkout -t origin/"$@"; }
alias gbd='git branch -D'
alias grs='git reset --hard HEAD'
alias gc='git commit'
alias gct='git commit -t'
alias grm='git ls-files --deleted | xargs git rm'
alias undopush='git push -f origin HEAD^:master'
alias undocommit='git reset --soft HEAD~1'
alias h='cd ~'
alias home='cd ~'
alias dotfiles='cd ~/.dotfiles'
alias dev="cd ~/dev/"
alias nom='rm -rf node_modules && npm cache clean --force && npm install'
alias rmnm="find . -name 'node_modules' -exec rm -rf '{}' +"
alias server='python3 -m http.server 1337'
alias df='df -h'
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias untar='tar -xvvf'
alias reload='exec $SHELL -l'
alias dsremove='find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch'
alias dsremover='find . -name .DS_Store -print0 | xargs -0 rm'
alias dsr='find . -name ".DS_Store" -depth -exec rm {} \;'

alias u="chezmoi update"

# macOS only
if [[ "$OSTYPE" == darwin* ]]; then
  alias rpsql='rm "$(brew --prefix)"/var/postgres*/postmaster.pid'
  alias fs="stat -f '%z bytes'"
  alias ifi="ifconfig | grep 'net'"
  alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'
  alias afk="pmset displaysleepnow"
  alias flush="sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder"
fi
