# path 
export MYBIN="$HOME/bin"
export BIN="/usr/local/bin"
export SBIN="/usr/local/sbin"
export NPM="/usr/local/bin/npm"
export HEROKU="/usr/local/heroku/bin"
export RBENV="$HOME/.rbenv/bin"
export PATH=$RBENV:$HEROKU:$NPM:$MYBIN:$BIN:$SBIN:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

# env variables 
export PGHOST=localhost
export EDITOR="vim"
export TERM=xterm-256color

# rbenv
eval "$(rbenv init -)"
