# Path 
export MYBIN="$HOME/bin"
export BIN="/usr/local/bin"
export SBIN="/usr/local/sbin"
export NPM="/usr/local/bin/npm"
export HEROKU="/usr/local/heroku/bin"
export RBENV="$HOME/.rbenv/bin"
export PIP="/Users/petebrousalis/Library/Python/2.7/bin"
export PATH=$PIP:$RBENV:$HEROKU:$NPM:$MYBIN:$BIN:$SBIN:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin

# Env
export PGHOST=localhost
export EDITOR="vim"
export TERM=xterm-256color
export DEV="~/dev"