# zsh (prezto)
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source "${HOME}/.zgen/zgen.zsh"

if ! zgen saved; then
  zgen prezto
  zgen prezto git
  zgen prezto command-not-found
  zgen prezto syntax-highlighting
  zgen prezto zsh-users/zsh-completions src
  zgen save
fi

# aliases
source $HOME/.aliases

# local config
[[ -a ~/.localrc ]] && source ~/.localrc

# rbenv
eval "$(rbenv init -)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
