# zsh config
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="steeef"
plugins=(git osx wd)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Aliases 
source $HOME/.aliases

# zsh completion
autoload -U compinit
compinit

# zsh options
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt COMPLETE_ALIASES 

# Local config
[[ -a ~/.localrc ]] && source ~/.localrc

# rbenv
eval "$(rbenv init -)"
