#!/bin/bash

cd "$(dirname "$0")/.."

# zsh
curl -L http://install.ohmyz.sh | sh

# brew
[ ! -d "/usr/local/.git" ] && [ "$(uname -s)" == "Darwin" ] && script/brew 

# apt
[ "$(uname -s)" != "Darwin" ] && sudo apt-get install build-essential zsh ack vim tmux

# rbenv
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

# ruby build
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# janus
curl -Lo- https://bit.ly/janus-bootstrap | bash

# update vim plugins
git submodule init
git submodule update

# symlink files
script/bootstrap

# switch shell to zsh
if [ $SHELL != '/bin/zsh' ]; then
  sudo chsh -s /bin/zsh $USER
fi
