#!/bin/bash

cd "$(dirname "$0")/.."

# rbenv
[ ! -d "$HOME/.rbenv" ] && git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

# ruby build
[ ! -d "$HOME/.rbenv/plugins/ruby-build" ] && git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# zsh
[ ! -d "$HOME/.oh-my-zsh" ] && curl -L http://install.ohmyz.sh | sh

# brew
[ ! -d "/usr/local/.git" ] && [ "$(uname -s)" == "Darwin" ] && script/brew 

# apt
[ "$(uname -s)" != "Darwin" ] && sudo apt-get install build-essential zsh ack vim tmux

# update vim plugins
git submodule update --init --recursive
git submodule foreach git pull

# symlink files
script/bootstrap

# vim plugins
vim +PluginInstall +qall

# switch shell to zsh
if [ $SHELL != '/bin/zsh' ]; then
  sudo chsh -s /bin/zsh
fi
