export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="steeef"

source $ZSH/oh-my-zsh.sh

for file in ~/.{,path,exports,aliases}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

autoload -U compinit
compinit

setopt APPEND_HISTORY # adds history
setopt INC_APPEND_HISTORY SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_REDUCE_BLANKS

setopt complete_aliases

[[ -a ~/.localrc ]] && source ~/.localrc



