#!/usr/bin/env bash

packages=(
align-regexp
atom-bracket-highlight
atom-clock
atom-react-autocomplete
auto-detect-indentation
autoclose-html
autocomplete-modules
busy-signal
close-tags
color-picker
distraction-free
editorconfig
git-plus
goto-definition
hey-pane
highlight-selected
hyperclick
intentions
js-hyperclick
language-babel
language-postcss
layout-control
less-than-slash
linter
linter-eslint
linter-json-lint
linter-ui-default
navigate
nerd-treeview
open-recent
project-manager
react
react-es6-snippets
react-snippets
symbol-gen
vim-mode-plus
);

apm install "${packages[@]}"

ln -snf ~/.dotfiles/atom/config.cson ~/.atom/config.cson
ln -snf ~/.dotfiles/atom/keymap.cson ~/.atom/keymap.cson
ln -snf ~/.dotfiles/atom/snippets.cson ~/.atom/snippets.cson
ln -snf ~/.dotfiles/atom/styles.less ~/.atom/styles.less
